apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1
  version: "1.32"

autoModeConfig:
  enabled: false

managedNodeGroups:
  - name: expense-ng
    instanceTypes:
      - t3.small
      - t3a.small
      - t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    spot: true
